#!/usr/bin/env sh
set -e

description="GPU cleanup for user $SLURM_JOB_USER, nodes $SLURM_JOB_NODELIST"
echo "Starting $description."

if ! command -v /usr/bin/nvidia-smi > /dev/null 2>&1; then
	echo "Skipping as nvidia-smi is not installed on this node."
	exit 0
fi

if [ $SLURM_JOB_UID -eq 0 ]; then
	echo "Skipping for user root."
	exit 0
fi

gpu_count=$(/usr/bin/nvidia-smi -L | wc -l)
nvidia_devices="$(/usr/bin/seq --separator=" " 0 $((gpu_count - 1)) | /usr/bin/sed -E 's|([[:digit:]]+)|/dev/nvidia\1|g')"
remaining_jobs="$(/usr/bin/squeue -h -u "$SLURM_JOB_USER" -w "$SLURM_JOB_NODELIST")"

if [ "$remaining_jobs" ]; then
	echo "Skipping as this is not the user's last job on the target nodes."
	exit 0
fi

# Suppress the exit status of fuser as it returns non-zero when there are no
# processes to kill
/usr/sbin/runuser -u "$SLURM_JOB_USER" -- /usr/bin/fuser -k $nvidia_devices || true

echo "Finished $description."
