- name: include kube-prometheus setup tasks
  block:
    - include_tasks: install_kube_prometheus.yml
  tags:
    - monitoring
    - kube-prometheus
  run_once: true
  delegate_to: localhost

- name: include external prometheus target tasks
  block:
    - include_tasks: configure_prometheus_targets.yml
  tags:
    - monitoring
    - prometheus-targets
  run_once: true
  delegate_to: localhost

- name: include ingress setup tasks
  block:
    - include_tasks: ingress.yml
  tags:
    - monitoring
    - monitoring-ingress
  run_once: true
  delegate_to: localhost
