---

- hosts: k8s
  become: true
  ignore_errors: true
  remote_user: ubuntu
  gather_facts: true
  vars:
    ansible_ssh_private_key_file: files/ikimk8s_rsa
  environment: "{{ k8s_env | default({}) }}"
  roles:
    - update
    - security


- hosts: infra
  become: true
  ignore_errors: true
  gather_facts: true
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - docker
    - security


- hosts: server
  become: true
  ignore_errors: true
  remote_user: ubuntu
  gather_facts: true
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - security


- hosts: gpucluster
  become: true
  ignore_errors: true
  remote_user: ubuntu
  gather_facts: true
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - update
    - security
    - g_nodes
    - proxies
    - ssh_config
    - docker
    - nvidia
    - miniconda
    - g_node_devtools
    - poetry


- hosts: ipaserver
  become: true
  ignore_errors: true
  gather_facts: true
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - update
    - security
    - proxies
    - docker
    - ipaserver
    - ipaserver_settings
    - users


- hosts: ipaclients
  become: true
  remote_user: ubuntu
  gather_facts: true
  environment: "{{ proxy_env | default({}) }}"
  pre_tasks:
    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - chrony
      tags: freeIPA-client
  roles:
    - role: freeipa.ansible_freeipa.ipaclient
      state: present
      tags: freeIPA-client
    - role: ipaclient_postinstall
    - role: subidmap


- hosts: managed_cluster
  become: true
  ignore_errors: true
  remote_user: ubuntu
  gather_facts: true
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - nfs_client


- hosts: managed_cluster_compute
  gather_facts: true
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - update
    - c_nodes
    - proxies
    - security


- hosts: nfs_servers
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - nfs_shares
    - user_skel


- hosts: tio
  become: true
  ignore_errors: true
  remote_user: ubuntu
  gather_facts: true
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - tio_users
    - user_skel


- hosts: ship
  become: true
  ignore_errors: true
  remote_user: ubuntu
  gather_facts: true
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - seafile
    - user_skel

- hosts: rke_k8s_cluster
  gather_facts: true
  remote_user: ubuntu
  roles:
    - proxies
    - set_default_gw
    - rke2
    - k8s_setup_longhorn

- hosts: rke_masters
  gather_facts: true
  remote_user: ubuntu
  roles:
    - k8s_setup_traefik
    - k8s_setup_monitoring

- hosts: server, infra, origin
  become: true
  remote_user: ubuntu
  gather_facts: true
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - telegraf_systemd
